name: Python SportCenter
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.A_SECRET_ID }}
          AWS_SECRET_ACCES_KEY: ${{ secrets.A_SECRET_PW }}
          AWS_REGION: ${{ secrets.A_REGION }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install dependencies and test
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: '5432'
        DB_NAME: ${{ secrets.DB_NAME }}
        SECRET_KEY: ""
        AWS_ACCESS_KEY: ""
        AWS_SECRET: ""
        AWS_BUCKET: ""
        AWS_REGION: ""
        WISE_TOKEN: ""
        WISE_URL: ""
        POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        POSTGRES_USER: ${{ secrets.DB_USER }}
        POSTGRES_DB: ${{ secrets.DB_NAME }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export PGPASSWORD="${{ secrets.DB_PASSWORD }}"
        pytest
